version: '3.8'
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5173:5173
    command: npm run dev
    container_name: dappethereum
    restart: always

