version: '3.8'
services:
  dappethereum:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5175:5175
    command: npm run dev
    container_name: dappethereum
    restart: always

